### ISSUE TITLE
How to display only one image in the preview?

### ISSUE THREAD

**Issue by virgiliomax** [peterfreeman/ngx-dropzone#51]
Does the component only support sending a single image/picture? How to center this image/picture or even use all the space in the preview area? I tried to change the properties in CSS, but without success.

**Comment by peterfreeman** [comment]
Hi there,

use this as a starting point:
```css
ngx-dropzone {
  justify-content: center;
}

ngx-dropzone-image-preview {
  height: unset;
  width: 100%;
}
```

You might have to make use of `::ng-deep` to get the css being applied correctly.

Happy coding! 🤓
